// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE81ibIgXEnQSi4DgINbMLip7wTgCMeuM',
    appId: '1:562498661328:web:ff129d331f82d4d79b67d5',
    messagingSenderId: '562498661328',
    projectId: 'todo-app-898d2',
    authDomain: 'todo-app-898d2.firebaseapp.com',
    storageBucket: 'todo-app-898d2.firebasestorage.app',
    measurementId: 'G-PLB5QPS153',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ZwBdPTQDRDwnFdZ8TW0PB1oqh9RYaNo',
    appId: '1:562498661328:android:a41c108b92c6f3ed9b67d5',
    messagingSenderId: '562498661328',
    projectId: 'todo-app-898d2',
    storageBucket: 'todo-app-898d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23-BIakHbG966Q5nE_DFXMz5t8exkAIk',
    appId: '1:562498661328:ios:beaa13e62cdbff979b67d5',
    messagingSenderId: '562498661328',
    projectId: 'todo-app-898d2',
    storageBucket: 'todo-app-898d2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23-BIakHbG966Q5nE_DFXMz5t8exkAIk',
    appId: '1:562498661328:ios:beaa13e62cdbff979b67d5',
    messagingSenderId: '562498661328',
    projectId: 'todo-app-898d2',
    storageBucket: 'todo-app-898d2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE81ibIgXEnQSi4DgINbMLip7wTgCMeuM',
    appId: '1:562498661328:web:d80609318271be719b67d5',
    messagingSenderId: '562498661328',
    projectId: 'todo-app-898d2',
    authDomain: 'todo-app-898d2.firebaseapp.com',
    storageBucket: 'todo-app-898d2.firebasestorage.app',
    measurementId: 'G-098H4NZM9Y',
  );
}
