// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRilG5i-byt3IPirmnfGz1s0R96YIwWOQ',
    appId: '1:811126124311:web:903eec4715103da5c11152',
    messagingSenderId: '811126124311',
    projectId: 'todo-app-85895',
    authDomain: 'todo-app-85895.firebaseapp.com',
    storageBucket: 'todo-app-85895.appspot.com',
    measurementId: 'G-L16S4GMCXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVGV9LxWLTYoYUSHgTlD8upAnGIKcmlY',
    appId: '1:811126124311:android:25e8a5261a62b203c11152',
    messagingSenderId: '811126124311',
    projectId: 'todo-app-85895',
    storageBucket: 'todo-app-85895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzKHIiy5SFHdc8ojmfsuntpYKRGehBiGM',
    appId: '1:811126124311:ios:22428f38a4a169eac11152',
    messagingSenderId: '811126124311',
    projectId: 'todo-app-85895',
    storageBucket: 'todo-app-85895.appspot.com',
    iosBundleId: 'com.example.todoAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzKHIiy5SFHdc8ojmfsuntpYKRGehBiGM',
    appId: '1:811126124311:ios:22428f38a4a169eac11152',
    messagingSenderId: '811126124311',
    projectId: 'todo-app-85895',
    storageBucket: 'todo-app-85895.appspot.com',
    iosBundleId: 'com.example.todoAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRilG5i-byt3IPirmnfGz1s0R96YIwWOQ',
    appId: '1:811126124311:web:1fbda7d03f0f2d60c11152',
    messagingSenderId: '811126124311',
    projectId: 'todo-app-85895',
    authDomain: 'todo-app-85895.firebaseapp.com',
    storageBucket: 'todo-app-85895.appspot.com',
    measurementId: 'G-D9V07QF13T',
  );

}